# Generated by Django 5.0.1 on 2024-01-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentstocks', '0002_member_quantity_member_registerdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('notificationContent', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
                ('barcode', models.IntegerField(null=True)),
            ],
        ),
    ]
