# Generated by Django 5.0.1 on 2024-01-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentstocks', '0003_suppliernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(null=True)),
                ('outboundTime', models.DateField(null=True)),
                ('receivedTime', models.DateField(null=True)),
            ],
        ),
    ]
