# Generated by Django 5.0.1 on 2024-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentstocks', '0005_rename_outboundtime_packagelog_outbounddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
