# Generated by Django 5.0.1 on 2024-01-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentstocks', '0006_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(null=True)),
            ],
        ),
    ]
