# Generated by Django 5.0.1 on 2024-01-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentstocks', '0007_allbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelog',
            name='outboundTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='packagelog',
            name='receivedTime',
            field=models.TimeField(null=True),
        ),
    ]
