# Generated by Django 5.0.1 on 2024-01-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentstocks', '0008_packagelog_outboundtime_packagelog_receivedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
